controller_list:
  - name: fake_elv_arm_controller
    joints:
      - elv_base_rotate_joint
      - elv_base_trans_joint
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
      - end_effector_joint