controller_list:
  - name: fake_arm_controller
    joints:
      - body_rotate_joint
      - elv_frame_updown_joint
      - arm_base_joint
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
      - arm_joint6