controller_list:
  - name: fake_manipulator_w_gripper_controller
    joints:
      - body_rotate_joint
      - trans_module_elv_joint
      - arm_base_joint
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
      - arm_joint6