arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  solve_type: Distance
  #solve_type can be Speed, Distance, Manipulation1, Manipulation2
  #Distance
  # kinematics_solver_attempts: 3