# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
sensors:
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /head2_d435/depth_registered/points
   max_range: 1.4
   point_subsample: 2
   padding_offset: 0.1
   padding_scale: 1.0
   filtered_cloud_topic: filtered_cloud