obstacle_height: 1.00  # assume something like an arm is mounted on top of the robot

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
inflation_radius: 0.54

map_type: costmap
publish_voxel_map: true
observation_sources: base_scan

base_scan: {sensor_frame: front_hokuyo_link, topic: front/scan, data_type: LaserScan, expected_update_rate: 1.5,
             observation_persistence: 0.0, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 1.0}

obstacle_layer:
  enabled:              true
  max_obstacle_height:  1.8
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             16
  unknown_threshold:    8
  mark_threshold:       0
  #track_unknown_space:  true    #true needed for disabling global path planning through unknown space
  obstacle_range: 2.5
  raytrace_range: 3.0
  origin_z: 0.0
  publish_voxel_map: true
  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    min_obstacle_height: 0.1
    max_obstacle_height: 0.8

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
#inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
